# -*- coding: utf-8 -*-
"""CSE111Lab9(PracticeSheet).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HN8OHFryIQ23pGY7oAS9X7LstSz2v8O3
"""

#1
class PlayerEarning:
  def __init__(self,name):
    self.name=name
    self.bonus=0
    self.total=0

  def calculateTotal(self,earning,goal=0):
    self.earning=earning
    self.goal=goal
    if goal==0:
      self.bonus=0
    elif goal>30:
       self.bonus = int((5/100) *earning+ 10000)
    else:
       self.bonus = int((5/100) * earning)
    self.total=int(self.earning+self.bonus)

  def printDetails(self):
    print(f"Player Name:{self.name}\nPlayer Season Earning without bonus:{self.earning}\nBonus:{self.bonus}\nPlayer Season Earning After Bonus:{self.total}")

print("**********************")
player1 = PlayerEarning('Buffon')
player1.calculateTotal(250000)
player1.printDetails()
print("\n**********************")
player2 = PlayerEarning('Dybala')
player2.calculateTotal(250000,
31)
player2.printDetails()
print("\n**********************")
player3 =PlayerEarning('Cuadrado')
player3.calculateTotal(250000,20)
player3.printDetails()

#2
class myList:
  def __init__(self,*numbers):
    self.numbers=numbers
    self.lst=[]
    #self.lst1=[]
    self.summation=0
    self.avg=0
    #self.merge=0
    for i in self.numbers:
      if i not in self.lst:
        self.lst.append(i)

  def sum(self):
    for i in self.lst:
      self.summation+=int(i)
    print(f"Sum:{self.summation}")

  def merge(self,*num):
    for i in num:
      self.lst.append(i)
      self.summation+=int(i)
        #self.lst1.append(i)
    #for j in self.lst1:
     # self.sum+=i
  def average(self):
    self.avg=self.summation/(len(self.lst))
    print(f"Average:{self.avg}")


l1 = myList(2,3,4,5,6) #you might need a list inside your class to store the values
l1.sum()
l1.merge(4,5,9)
l1.sum()
l1.average()
print("-----------------------------")
l2 = myList()
l2.average()
l2.merge(1,2,4,8)
l2.sum()

#5
class Smartphone:
  def __init__(self,name,model):
    self.name=name
    self.model=model
  def addFeature(self,display,size):
    self.display=display
    self.size=size
    
s1 = Smartphone()
print("=================================")
s1.addFeature("Display", "6.1 inch")
print("=================================")
s1.setName("Samsung Note 20")
s1.addFeature("Display", "6.1 inch")
s1.printDetail()
print("=================================")
s2 = Smartphone("Iphone 12 Pro")
s2.addFeature("Display", "6.2 inch")
s2.addFeature("Ram", "6 GB")
print(=================================")
s2.printDetail()
s2.addFeature("Display", "Amoled panel")
s2.addFeature("Ram", "DDR5")
print("=================================")
s2.printDetail()
print("=================================")

